### ISSUE TITLE
Issue with trigger_on

### ISSUE THREAD

**Issue by drhey** [sensu-plugins/sensu-plugins-sensu#25]
I am able to use handler-sensu.rb for remediation. However, I am seeing that it attempts to run on ALL machines in a given subscription. For example, say I have two machines in a subscription called "clients" and when `sshd` goes down on one of them, the remediator tries to run the remediation (restarting sshd) on BOTH. I can see this by tailing `/var/log/secure` on both machines. Also, this is evidenced by the fact that one machine, intentionally, doesn't have a sudoers.d file for the sensu user that would attempt to run this remediation. When it attempts to run on this machine, and can't due to lack of permissions, it notes the issue in Uchiwa - which gives a warning with the output of the sudo lecture a user sees at first-run of sudo. It also notes this failed attempt in `/var/log/secure` on the machine, as one would expect.

Any ideas?

EDIT: I realize that `trigger_on` is intended to run against groups as per the comments in the code:

> An array of subscriptions may be specified via a 'trigger_on' property outside of the 'remediation' dictionary (in the 'check' dictionary).

But I can't get the remediator to even run on a given host without having `trigger_on` defined

**Comment by majormoses** [comment]
What I did to solve this in my setup is to include a subscription is to use a name that is unique to the hostname.

Process check:
```json
{
  "checks": {
    "<REDACTED_SERVICE_NAME>": {
      "command": "check-process.rb -p 'java .* -jar <REDACTED_REGEX_TO_MATCH_PROCESS>r'",
      "subscribers": [
        "<REDACTED_SERVICE_NAME>"
      ],
      "handlers": [
        "pagerduty",
        "remediator"
      ],
      "interval": 15,
      "pager_team": "non_urgent",
      "notification": "No <REDACTED_SERVICE_NAME> java process is running",
      "occurrences": 4,
      "remediation": {
        "<REDACTED_SERVICE_NAME>_process_remediate": {
          "occurrences": [
            "1-5"
          ],
          "severities": [
            2
          ]
        }
      }
    }
  }
}
```

Remediator check:
```json

{
  "checks": {
    "<REDACTED_SERVICENAME>_process_remediate": {
      "command": "sudo -u <REDACTED_SERVICE_USER> service <REDACTED_SERVICE_NAME> restart",
      "subscribers": [
        "<REDACTED_SERVICE_NAME>",
        "ip-10-55-142-253.us-west-2.compute.internal"
      ],
      "standalone": false,
      "handlers": [
        "pagerduty"
      ],
      "publish": false,
      "interval": 10,
      "pager_team": "non_urgent",
      "notification": "Remediate failed: Can not start <REDACTED_SERVICE_NAME> service",
      "occurrences": 3
    }
  }
}
```

sensu client.json:
```json
{
  "client": {
    "address": "10.55.142.253",
    "subscriptions": [
      "ip-10-55-142-253.us-west-2.compute.internal",
      "base",
      "<REDACTED_SERVICE_NAME>"
    ],
    "name": "ip-10-55-142-253.us-west-2.compute.internal",
    "chef": {
      "client": {
        "node": "ip-10-55-142-253.us-west-2.compute.internal"
      }
    },
    "safe_mode": true,
    "keepalive": {
      "handler": "sensu-deregister",
      "thresholds": {
        "warning": 40,
        "critical": 60
      }
    }
  }
}

```

**Comment by majormoses** [comment]
@drhey did that solve your problem?

**Comment by drhey** [comment]
@majormoses I've been ruminating on your suggestion since you mentioned it, because my situation is a bit different. I have over 1300 machines that share services that might need to be handled/remediated. So, I'm having a difficult time thinking of how each machine could be made "unique" to make this plugin work/strategy, without introducing a ton of complexity into our configuration management system.

For the sake of context: Right now, we're leveraging ansible groups to pare various machines together, and my sensu subscriptions are based on those ansible groups when the machines are built (or the sensu client role is deployed to them). So, by that logic the machines do have some semblance of uniqueness. One of the services we monitor for is logstash. I would like to make it so, if an alert comes through that logstash isn't running, then go ahead and restart it on that node - not on all machines that have the logstash role, which appears to be the behavior I've observed.

Perhaps I've misunderstood your suggestion? 

Thanks for reaching out!

**Comment by majormoses** [comment]
Unless I am misunderstanding you then we have basically the same setup with chef. So this is what you can do to fix it:
1. Add the hostname as a subscription to the client
1. Add the subscription to the remediation check

If you need more help hit me up in IRC and we can chat about it.

**Comment by majormoses** [comment]
@drhey just checking after the zoom I hopped on with you if you still need help setting this up?

**Comment by drhey** [comment]
@majormoses I've not yet had a chance to implement it, but I still recall the basic building blocks. Appreciate the follow up. I might have a question later on down the road, but am currently juggling some priorities with our sensu setup.

**Comment by drhey** [comment]
@majormoses Just wanted to follow up and let you know that I did get this working. Thanks for the assist! It really helped.
