### ISSUE TITLE
Sensu-Remediator not executing the required command

### ISSUE THREAD

**Issue by amruthapbhat** [sensu-plugins/sensu-plugins-sensu#26]
Hi,
I have a nexus process which is being monitored with sensu. Now i want to start the nexus process from sensu if its stopped .

I have given the below remediation configs.

check-process.json
```json
{
  "checks": {
    "check_process": {
      "command": "/etc/sensu/plugins/check-process.rb -p /usr/lib/jvm/java-8-oracle/jre/bin/java -W 1",
      "interval": 120,
      "subscribers": [ "nexus-server-sensu-client" ],
      "handlers": [ "remediator" ],
      "remediation": {
         "check_remediation": {
            "occurrences": ["1+"],
            "severities": [2]
        }
     }
   }
  }
}
```

check-nexus.json:
```json
  "checks": {
    "check_remediation": {
      "command": "sudo /usr/local/nexus-3.0.2-02/bin/nexus run",
      "subscribers": [ "nexus-server-sensu-client" ],
      "handlers": [ "remediator" ],
      "standalone": false,
      "publish": false
    }
  }
}
```

remeadiator.json
```json
{
  "handlers": {
    "remediator": {
      "command": "/etc/sensu/handlers/sensu.rb",
      "type": "pipe",
      "severities": ["critical"]
    }
  }
}
```

client.json:
```json
  "client": {
    "name": "check-process",
    "address": "IP address of the server",
    "subscriptions": ["nexus-server-sensu-client"],
    "safe_mode":false
  }
}
```
I have placed the handler at /sensu/handlers/sensu.rb which i have taken from the below path
https://github.com/sensu-plugins/sensu-plugins-sensu/blob/master/bin/handler-sensu.rb

The output of the sensu-client:
{"timestamp":"2017-06-05T10:35:45.938499+0000","level":"info","message":"received check request","check":{"command":"/etc/sensu/plugins/check-process.rb -p /usr/lib/jvm/java-8-oracle/jre/bin/java -W 1","handlers":["remediator"],"remediation":{"check_remediation":{"occurrences":["1+"],"severities":[2]}},"name":"check_process","issued":1496658945}}
{"timestamp":"2017-06-05T10:35:46.087514+0000","level":"info","message":"publishing check result","payload":{"client":"check-process","check":{"command":"/etc/sensu/plugins/check-process.rb -p /usr/lib/jvm/java-8-oracle/jre/bin/java -W 1","handlers":["remediator"],"remediation":{"check_remediation":{"occurrences":["1+"],"severities":[2]}},"name":"check_process","issued":1496658945,"interval":120,"subscribers":["nexus-server-sensu-client"],"executed":1496658945,"duration":0.148,"output":"CheckProcess CRITICAL: Found 0 matching processes; cmd //usr/lib/jvm/java-8-oracle/jre/bin/java/\n","status":2}}}

The sensu-server log:

{"timestamp":"2017-06-05T10:47:46.334224+0000","level":"info","message":"handler output","handler":{"command":"/etc/sensu/handlers/sensu.rb","type":"pipe","severities":["critical"],"name":"remediator"},"output":["REMEDIATION: Evaluating remediation: check-process {\"check_remediation\"=>{\"occurrences\"=>[\"1+\"], \"severities\"=>[2]}} #=556 sev=2\nREMEDIATION: Triggering remediation check 'check_remediation' for [\"check-process\"]\nREMEDIATION: Received API Response (202): {\"issued\":1496659666}, exiting.\n"]}

The response shown is as issued, but the command given in the remediator i.e : check-nexus.json is not executing

Could you let me know if i am missing out any config?

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-process-checks/issues/44#issuecomment-306248496
