### ISSUE TITLE
check-aggregate.rb based on severities

### ISSUE THREAD

**Issue by maxpwil** [sensu-plugins/sensu-plugins-sensu#30]
In our use case we need the check-aggregate.rb to alert based on the severities of the aggregated checks. Currently it is only possible to alert based on `non-ok` (warning + critical).

According to the option descriptions this should be possible with the `warning_count` and `critical_count` option, which is not the case:
* `warning_count`: `number of nodes in warning before warning` 
* `critical_count`: `number of node in critical before critical` 

the check just alerts based on non-ok, just like with the `warning` and `critical` option.

Example of what we need:
`warning`=5
`critical`=5

`{:ok=>5, :warning=>5, :critical=>0, :unknown=>0, :total=>10, :stale=>0}` => warning
`{:ok=>5, :warning=>0, :critical=>5, :unknown=>0, :total=>10, :stale=>0}` => critical
(currently both examples would result in a critical)

For us it would be more suitable to use `warning` and `critical` as we don't care about the exact number of nodes, but about a certain percentage threshold.

I already created a pull request https://github.com/sensu-plugins/sensu-plugins-sensu/pull/27, which adds a `ignore-severity` option to ignore the severities, like it currently is. The new default behaviour would change to alert based on severities.
Another option would be to keep the current default behaviour and a option which allows to alert based on severities.

**Comment by majormoses** [comment]
@Moozaliny thanks for the extra context after listening t your very sound use case which is honestly what I would have expected check to do before reading the code. I feel that the code just does not make sense as the default way to approach this. I think your proposal makes a lot of sense in this very backwards scenario and if we were writing it from scratch I would default to specific thresholds and have an option to combine non ok thresholds kinda like we are porposing (not sure how I feel about that and unknown I think I would specifically handle crits and warns or require another option) to be evaluated by thresholds. @eheydrick do you feel differently?

**Comment by majormoses** [comment]
closed via #27
